### ISSUE TITLE
old instances not working 

### ISSUE THREAD

**Issue by ahmednosman** [cartologic/cartoview_feature_list#15]
please check this instance as it never loads
http://try.cartoview.net/apps/cartoview_feature_list/816/view/#map=19.109257071294063/-8389527.58/5337062.63/0

**Comment by hishamkaram** [comment]
![screen shot 2017-10-16 at 3 14 05 pm](https://user-images.githubusercontent.com/24391550/31613882-1da3fc00-b28d-11e7-980f-dd2c5b3b89bb.png)
